### PR TITLE
feat: added hiring call out

### PR DESCRIPTION
**Pull request by RistoBIn**

### CODE REVIEW

**Comment by ianaya89** [comment]
@RistoBIn can you take a look at conflicts?
@orcunilbeyli is this ok to merge?

**Comment by orcunilbeyli** [comment]
> @RistoBIn can you take a look at conflicts?
> @orcunilbeyli is this ok to merge?

I am holding this issue @ianaya89 . I know this is open for a bit long time but I gotta update the design.

**Comment by ianaya89** [comment]
@orcunilbeyli just checking in. Should we keep this open?

**Comment by orcunilbeyli** [comment]
Let's close this @ianaya89. We've added the callout to the footer. We can revisit if any more improvement is needed. Closing it.

**Pull request closed without merging**
