### PR TITLE
feat: move some assets to S3 [sc-00]

### PR DESCRIPTION
**Pull request by maxigimenez**
## Affected Components
* [ ] Content & Marketing
* [ ] Pricing
* [ ] Test
* [ ] Docs
* [ ] Learn
* [ ] Other

## Pre-Requisites
* [x] Code is linted (`npm run lint`)

## Notes for the Reviewer
I've moved a few of the big assets to S3 + load Inter font from google apis

### CODE REVIEW

**Review by ndom91 — COMMENTED** [review]
You setup cloudfront, right?

I think the URL's need to be changed then to the hostname cloudfront gives you (which its pointing at a specific bucket, right?). Then you can keep the same path afaik

See: https://stackoverflow.com/a/23544112/9579094

**Comment by ndom91** [comment]
Also I ran this preview URL and our main `checklyhq.com` domain through pagespeed.web.dev. The preview URL came in a few points below the prod site, but it was mostly for issues totally unrelated to this PR / these files, and because the preview URL doesn't have good cache headers set by Vercel. So all in all, I think theres no (major) performance worries we need to have beacuse of these changes :+1:

**Comment by maxigimenez** [comment]
@ndom91 good catch, updated to use cloudfront properly

**Review by ndom91 — APPROVED** [review]
LGTM 👍

**Pull request merged**
