### PR TITLE
Add launch video to CLI guide

### PR DESCRIPTION
**Pull request by hlenke**
## Affected Components
* [ ] Content & Marketing
* [ ] Pricing
* [ ] Test
* [ ] Docs
* [x ] Learn
* [ ] Other

## Pre-Requisites
* [ ] Code is linted (`npm run lint`)

### CODE REVIEW

**Comment by tnolet** [comment]
@hlenke changed it to use the built-in youtube short code.

**Review by tnolet — APPROVED** [review]
Made a small change, otherwise good.

**Comment by hlenke** [comment]
🤦‍♂️ why haven't I seen that? 
But we are losing the `start` at option. 
@tnolet

**Comment by tnolet** [comment]
@hlenke yeah, that is a downside. Maybe we can add segments to the video.

**Comment by hlenke** [comment]
@tnolet yeah, we should cut the video eventually. Let's leave it as is for today.

**Comment by stefanjudis** [comment]
@hlenke Just FYI, cutting and reuploading means a new YT URL and there are segments on the video already. :)

**Pull request merged**
