### PR TITLE
guides: e2e monitoring of crucial user flows

### PR DESCRIPTION
**Pull request by adamwardecki**

### CODE REVIEW

**Comment by adamwardecki** [comment]
I have one issue here. The tab containing the code snippet is initially hidden:

https://checklyhq-com-git-adamwardecki-sc-000checkly-sig-082860-checkly.vercel.app

Can't figure out why is this happening :/

**Comment by ragog** [comment]
Hey @adamwardecki, awesome that you wrote down this content! We definitely can use more of this :)
Before I dive into a proper review, I must ask: does this -need- to be a guide? (as in a content piece specifically for our learn/guides section on checklyhq.com)
Asking because this seems like it could be expanded just a bit to become a pretty interesting blog post for blog.checklyhq.com. If we instead want to have it as a guide, we need to tweak a few things to match the format (I can guide you there).

CC @Haubersch

**Comment by adamwardecki** [comment]
@ragog I just went with my gut here. We can totally do a blog post 👍

**Review by ianaya89 — APPROVED** [review]
💯

**Pull request closed without merging**
