### PR TITLE
added video in the synthetic-monitoring page

### PR DESCRIPTION
**Pull request by RistoBIn**

### CODE REVIEW

**Review by tnolet — CHANGES_REQUESTED** [review]
@RistoBIn @orcunilbeyli the video stops playing with every tiny scroll interaction. That is unexpected. I would expect the video to pause only when it scroll out of the viewport.

**Comment by orcunilbeyli** [comment]
> @RistoBIn @orcunilbeyli the video stops playing with every tiny scroll interaction. That is unexpected. I would expect the video to pause only when it scroll out of the viewport.

Yes exactly. @RistoBIn 👆

**Review by tnolet — CHANGES_REQUESTED** [review]
@RistoBIn It still stops playing the video every tiny scroll I do on the page. I think we should just not stop playing the video on scroll or make the video stop when the video scrolls out of the viewport.

**Comment by RistoBIn** [comment]
@tnolet 
In which page are you testing?
Are you testing on the synthetic monitoring page?

**Comment by tnolet** [comment]
> @tnolet
> In which page are you testing?
> Are you testing on the synthetic monitoring page?

@RistoBIn yes, I'm looking at https://checklyhq-com-git-issue-synthetic-monitoring-page-checkly.vercel.app/product/synthetic-monitoring/

**Comment by RistoBIn** [comment]
Oh, sorry.
The latest change is not committed.

**Review by tnolet — APPROVED** [review]
LGTM

**Pull request merged**
