### PR TITLE
docs: CLI document new group property for checks

### PR DESCRIPTION
**Pull request by clample**
## Affected Components
* [ ] Content & Marketing
* [ ] Pricing
* [ ] Test
* [x] Docs
* [ ] Learn
* [ ] Other

## Notes for the Reviewer
https://github.com/checkly/checkly-cli/pull/547 makes changes to assigning checks to groups with the Checkly CLI. This PR updates the docs accordingly.

Old syntax:
```
new BrowserCheck('logicalId', { groupId: group.ref() })
```

New syntax:
```
new BrowserCheck('logicalId', { group })
```

The relevant page is [Using Constructs](https://checklyhq-com-git-chrislample-cli-use-new-group-config-checkly.vercel.app/docs/cli/constructs/).

### CODE REVIEW

**Review by tnolet — APPROVED** [review]
LGTM

**Comment by tnolet** [comment]
@clample we need to also update the examples

**Comment by clample** [comment]
@tnolet the examples in the checkly-cli repo? I handled that with https://github.com/checkly/checkly-cli/pull/547.

**Review by tnolet — COMMENTED** [review]
LGTM

**Comment by clample** [comment]
Thanks @tnolet

**Comment by clample** [comment]
@tnolet sorry, it looks like you left a comment rather than a full approval

**Review by tnolet — APPROVED** [review]
LGTM

**Pull request merged**
