### PR TITLE
Docs vercel integration

### PR DESCRIPTION
**Pull request by ragog**

### CODE REVIEW

**Review by jan-osch — APPROVED** [review]
LGTM. 

One thing is missing IMO: we should show how to consume the fruits of the Vercel integration. Show the users where to find the Deployments page with a sample Vercel deployment, and also the `CI/CD TRIGGERED CHECK RESULTS` tab in check results.

**Comment by ragog** [comment]
@jan-osch great feedback. I added a new section to show both. Let me know what you think.

**Review by jan-osch — APPROVED** [review]
Somehow I cannot preview the updated version. But the code is looking good.

**Review by jan-osch — APPROVED** [review]
Bellissimo 👌

**Pull request merged**
