### PR TITLE
feat: case studies redesign

### PR DESCRIPTION
**Pull request by pilimartinez**
## Affected Components
* [X] Content & Marketing
* [ ] Pricing
* [ ] Test
* [ ] Docs
* [ ] Learn
* [ ] Other

## Pre-Requisites
* [X] Code is linted (`npm run lint`)

## Notes for the Reviewer

Redesign of case studies page.
## Screenshots

image

### CODE REVIEW

**Comment by tnolet** [comment]
this is amazing. Only comment I have is we want to see if we can compress the logo images a bit. Non-lossy compression.

**Comment by maxigimenez** [comment]
So many logos 😍

**Comment by pilimartinez** [comment]
> this is amazing. Only comment I have is we want to see if we can compress the logo images a bit. Non-lossy compression.

Thanks! wasn't sure how to compress them but did it with an online site, should be better now.

**Review by maxigimenez — APPROVED** [review]
LGTM 👍

**Pull request merged**
