### PR TITLE
ci: adds some logic to not update the algolia index on each run [ch-000]

### PR DESCRIPTION
**Pull request by tnolet**
@ianaya89 @ndom91 have a short peek if this makes sense. I tested it locally and seems to work

### CODE REVIEW

**Comment by tnolet** [comment]
hmm, seems to crap out on `HEAD^`

**Comment by ndom91** [comment]
Hmm okay so you want to just run the certain jobs only if their respective files have changed? We had a good solutino for this in one of the next-auth repos at some point. Let me check if I can dig it back up.

**Comment by ianaya89** [comment]
@tnolet is this ready for review?

**Comment by tnolet** [comment]
> @tnolet is this ready for review?

@ianaya89 yes, this is ready for review and merge. We could also explore @ndom91's option, but this works for now

**Review by ianaya89 — APPROVED** [review]

**Pull request merged**
