### PR TITLE
fix: run algolia-docsearch action only on pushes to main [sc-00]

### PR DESCRIPTION
**Pull request by ndom91**
## Affected Components
* [ ] Content & Marketing
* [ ] Pricing
* [ ] Test
* [ ] Docs
* [ ] Learn
* [x] Other

## Pre-Requisites
* [ ] Code is linted (`npm run lint`)

## Notes for the Reviewer

- Run the `algolia-docsearch` action only on pushes to `main`, i.e. only on PR merges. Instead of on every push.

### CODE REVIEW

**Review by miliberlin — APPROVED** [review]

**Comment by ndom91** [comment]
> @ndom91 this seems to block itself. Maybe running it against an [approved PR](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-a-workflow-when-a-pull-request-is-approved) would be better?

Yeah potentially, but this should work, this is how we do it in all other repos. It technically shouldn't run any of thse steps in the workflow, like `scrape-docs` and `scrape-learn`, because we're not `push`ing to `main` yet (until the merge ocmmit at the end when we merge)

**Comment by ndom91** [comment]
Looks like its still attempting the `scrape-*` jobs though.. i'll try adding that clause you mentioned to those two steps :+1:

**Comment by ndom91** [comment]
Yeah you know what, I think this is already being done. I.e. its only running these algolia scrape jobs on merge's to `main`.

See for example this "merging main into the feature branch", i.e. just hit "Update branch" on a PR (https://github.com/checkly/checklyhq.com/actions/runs/4283096766), where the scrape jobs didn't run.

But then the actual merge of that branch / PR into `main` *did* run the scrape jobs (https://github.com/checkly/checklyhq.com/actions/runs/4283120123)

**Comment by ndom91** [comment]
The "right" way to run it only on pushes to `main`, is to put it in the global workflow `on:` parameter at the top fo the workflow file, but the way we're doing it already here works as well.. so I'll just leave it for now

**Pull request closed without merging**
