### PR TITLE
docs: add YT GH sync video link

### PR DESCRIPTION
**Pull request by stefanjudis**
## Affected Components
* [ ] Content & Marketing
* [ ] Test
* [x] Docs
* [ ] Learn
* [ ] Other

Adding YT link.

### CODE REVIEW

**Comment by tnolet** [comment]
@stefanjudis it's kaput

**Comment by stefanjudis** [comment]
@tnolet It's heile again!

**Comment by tnolet** [comment]
Wunderbar

**Review by tnolet — APPROVED** [review]
LGTM

**Pull request merged**
